# -*- coding: utf-8 -*-
"""Month 1 / Week 1 — FIA + income riders. Every rendered piece is defined here.
   *stars* around a phrase render it in the gold gradient."""

FOOT = dict(footL='HERRON & CO. LEGACY AGENCY', footR='NPN 21556594')
D_ILL = 'Illustrative only — not an offer of coverage or a quoted rate.'
D_CAP = 'Caps and participation rates are set by the carrier and can change. No dividends.'
D_CARR = 'Guarantees backed by the issuing carrier’s claims-paying ability. Not FDIC insured.'
D_TAX = 'General education, not individualized tax or legal advice.'

# ─────────────────────────────────────────────────────────────── IMAGES (6)
IMAGES = [
    dict(slug='the-floor', scene='floor_slab', seed=3, anchor='bottom', titleSize=76,
         eyebrow='THE FLOOR', title='Same market.\n*Different floor.*',
         sub='INDEX −20%   ·   CREDIT 0.00%',
         disc=D_ILL + ' ' + D_CAP, p=dict(l1='CREDIT 0.00%', l2='INDEX −20%'), **FOOT),
    dict(slug='cap-and-floor', scene='capped_column', seed=11, anchor='bottom', titleSize=70,
         eyebrow='WHAT IT COSTS', title='The ceiling is the price of *the floor.*',
         sub='WHAT SPILLS OVER IS WHAT IT COSTS',
         disc=D_ILL + ' ' + D_CAP,
         p=dict(level=.62, lc='CAP', lf='FLOOR', l2='CARRIER KEEPS'), **FOOT),
    dict(slug='pile-vs-paycheck', scene='pile_vs_paycheck', seed=23, anchor='bottom', titleSize=74,
         eyebrow='TWO JOBS, TWO TOOLS', title='One is a pile.\nOne is a *paycheck.*',
         sub='THE EMPTY CHAMBER STILL PAYS',
         disc=D_CARR + ' ' + D_ILL, **FOOT),
    dict(slug='benefit-base', scene='wireframe_cube', seed=31, anchor='bottom', titleSize=68,
         eyebrow='ASK WHICH NUMBER', title='The bigger number *isn’t your money.*',
         sub='BENEFIT BASE  ≠  CASH VALUE',
         disc='A benefit base is generally not available as a withdrawal or death benefit. ' + D_ILL,
         p=dict(l1='CASH VALUE', l2='BENEFIT BASE', l3='NOT WITHDRAWABLE'), **FOOT),
    dict(slug='sequence-of-returns', scene='staircase', seed=41, anchor='bottom', titleSize=68,
         eyebrow='SEQUENCE RISK', title='It’s not the average.\nIt’s *the order.*',
         sub='−20% NEEDS +25%   ·   −40% NEEDS +67%',
         disc='Illustrative math, not a projection of any product.',
         p=dict(broken=3, l1='−20% NEEDS +25%'), **FOOT),
    dict(slug='direct-vs-indirect', scene='conduit', seed=61, anchor='bottom', titleSize=66,
         eyebrow='MOVING RETIREMENT MONEY', title='Never let it *touch your hands.*',
         sub='DIRECT TRANSFER · 0 DAYS · 0 WITHHOLDING',
         disc=D_TAX + ' Confirm your situation with your CPA.',
         p=dict(severed=False, l1='DIRECT · TRUSTEE TO TRUSTEE'), **FOOT),
]

# ──────────────────────────────────────────────────────────── CAROUSELS (6)
def sl(scene, title, size=64, anchor='bottom', eyebrow=None, sub=None, seed=1, p=None, **kw):
    d = dict(scene=scene, title=title, titleSize=size, anchor=anchor, seed=seed, p=p or {}, **FOOT)
    if eyebrow: d['eyebrow'] = eyebrow
    if sub: d['sub'] = sub
    d.update(kw)
    return d


CAROUSELS = [
 dict(slug='the-floor', slides=[
   sl('value_block', 'A 25% average that pays you *$0.*', 62, eyebrow='SLIDE 01 · THE FLOOR',
      seed=2, p=dict(value='25%', crackAt=0.1, l1='THE AVERAGE THAT PAID NOTHING')),
   sl('bar_pair', 'Year one: up 100%. Feels great.', 60, seed=5,
      p=dict(h1=3.0, h2=0.02, t1='YEAR 1  +100%', t2='')),
   sl('bar_pair', 'Year two: down 50%. Still "averages" 25%.', 56, seed=6,
      p=dict(h1=3.0, h2=1.5, avg='AVERAGE  +25%')),
   sl('flatline', 'Your actual account: back to even.', 60, seed=7, p=dict(l1='NET CHANGE  $0')),
   sl('hourglass_pair', 'At 25 you have time. At 55 you don’t.', 58, seed=8,
      p=dict(l1='AGE 25', l2='AGE 55')),
   sl('floor_slab', 'A floor means the index can’t take principal.', 54, seed=3,
      p=dict(l1='CREDIT 0.00%', l2='INDEX −20%')),
   sl('capped_column', 'The price of the floor is *a cap on top.*', 56, seed=11,
      p=dict(level=.66)),
   sl('mark_end', 'I’ll run *your* numbers. Not a sales pitch.', 56, seed=99,
      kw='FLOOR', disc=D_ILL + ' ' + D_CAP, p=dict(cy=.34)),
 ]),
 dict(slug='pile-or-paycheck', slides=[
   sl('pile_vs_paycheck', '"Annuity" isn’t a product. It’s a *category.*', 58,
      eyebrow='SLIDE 01 · PILE OR PAYCHECK', seed=23),
   sl('value_block', 'A fixed annuity is a parking spot.', 60, seed=24,
      p=dict(value='MYGA', size=78, l1='SET RATE · SET TERM')),
   sl('bar_pair', 'Set rate. Set term. Then you walk.', 60, seed=25,
      p=dict(h1=2.2, h2=2.6, t1='PREMIUM', t2='TERM END')),
   sl('gear_mech', 'An income rider is a faucet.', 62, seed=26,
      p=dict(l1='OPTIONAL RIDER', l2='PAID MONTHLY')),
   sl('value_block', 'It’s optional. It has *an annual cost.*', 58, seed=27,
      p=dict(value='~1%/YR', size=104, l1='TYPICAL RIDER CHARGE')),
   sl('wireframe_cube', 'It grows a benefit base — not cash.', 56, seed=31,
      p=dict(l1='CASH VALUE', l2='BENEFIT BASE', l3='NOT WITHDRAWABLE')),
   sl('gear_mech', 'Switch it on: paid for life. Even at zero.', 54, seed=28,
      p=dict(l1='LIFETIME INCOME', l2='EVEN AT $0 VALUE')),
   sl('mark_end', 'Ask which number you can *actually walk out with.*', 52, seed=98,
      kw='RIDER', disc='Riders are optional and typically carry an annual charge. ' + D_CARR,
      p=dict(cy=.34)),
 ]),
 dict(slug='the-20-percent-drop', slides=[
   sl('twin_columns', 'The S&P drops 20%. Watch two accounts.', 56,
      eyebrow='SLIDE 01 · THE DROP', seed=15, p=dict(a=.8, b=.8, drain=False,
      va='$100,000', vb='$100,000')),
   sl('twin_columns', 'Account A: $100,000 → $80,000.', 60, seed=16,
      p=dict(a=.64, b=.8, drain=False, va='$80,000', vb='$100,000')),
   sl('twin_columns', 'Account B: credit 0.00%. Not −20%.', 58, seed=17,
      p=dict(a=.64, b=.8, drain=False, va='$80,000', vb='$100,000')),
   sl('staircase', 'A needs +25% just to get even.', 60, seed=41, p=dict(broken=3,
      l1='−20% NEEDS +25%')),
   sl('flatline', 'B starts next year at full value.', 60, seed=18, p=dict(l1='$100,000')),
   sl('capped_column', 'The trade: your upside gets *capped.*', 58, seed=11, p=dict(level=.78)),
   sl('fee_stack', 'No dividends. Fees and withdrawals still count.', 52, seed=19,
      p=dict(labels=['WITHDRAWALS', 'RIDER CHARGE'])),
   sl('mark_end', 'Down 40% needs *+67%* to break even.', 56, seed=97,
      kw='DROP', disc=D_CAP + ' ' + D_ILL, p=dict(cy=.34)),
 ]),
 dict(slug='one-lump-or-two', slides=[
   sl('value_block', 'One lump or two? Retirement’s real question.', 54,
      eyebrow='SLIDE 01 · LUMP OR INCOME', seed=51,
      p=dict(value='$300,000', size=78, l1='THE PILE YOU BUILT')),
   sl('split_cube', 'Option 1: keep the lump. Full control.', 58, seed=52,
      p=dict(split=.05, l1='YOU MANAGE IT', l2='')),
   sl('bar_pair', 'Pull 4% → $12,000 a year on $300k.', 56, seed=53,
      p=dict(h1=3.0, h2=.5, t1='$300,000', t2='$12,000/YR')),
   sl('staircase', 'Market drops? That ribbon should shrink.', 58, seed=54,
      p=dict(broken=2, l1='WITHDRAWING INTO A DRAWDOWN')),
   sl('gear_mech', 'Option 2: convert part into lifetime income.', 54, seed=55,
      p=dict(l1='LIFETIME PAYOUT', l2='FOR LIFE')),
   sl('value_block', 'Illustrative 5.5% payout → $16,500 for life.', 52, seed=56,
      p=dict(value='$16,500', size=72, l1='ILLUSTRATIVE · PER YEAR · FOR LIFE')),
   sl('split_cube', 'Best answer for most people: *split it.*', 56, seed=57,
      p=dict(split=.42, l1='LIQUID', l2='INCOME')),
   sl('mark_end', 'Cover the bills. Keep the rest *liquid.*', 56, seed=96,
      kw='LUMP', disc='Payout factors vary by age, product, state and date and are set by the '
      'carrier — 5.5% is illustrative. ' + D_CARR, p=dict(cy=.34)),
 ]),
 dict(slug='what-it-actually-costs', slides=[
   sl('fee_stack', '"Annuities are full of hidden fees." Partly true.', 52,
      eyebrow='SLIDE 01 · THE REAL COSTS', seed=71),
   sl('fee_stack', 'Variable annuities can stack real charges.', 56, seed=72,
      p=dict(labels=['RIDER', 'ADMIN', 'SUB-ACCOUNT', 'M&E'])),
   sl('fee_stack', 'That criticism is fair. I’ll say it out loud.', 54, seed=73,
      p=dict(labels=['RIDER', 'ADMIN', 'SUB-ACCOUNT', 'M&E'])),
   sl('fee_stack', 'Most fixed index contracts: no explicit annual fee.', 50, seed=74,
      p=dict(clean=True, l1='NO EXPLICIT ANNUAL FEE')),
   sl('capped_column', 'So the carrier gets paid *at the cap.*', 58, seed=11,
      p=dict(level=.9, l2='CARRIER KEEPS')),
   sl('gear_mech', 'Add an income rider → a real annual charge.', 54, seed=75,
      p=dict(l1='RIDER CHARGE', l2='TYP. UNDER ~1%/YR')),
   sl('ring60', 'Break it early → surrender charges bite.', 56, seed=76,
      p=dict(left=.55, l1='SURRENDER', l2='KNOW THE SCHEDULE')),
   sl('mark_end', 'Cap. Rider cost. Surrender schedule. *In writing.*', 50, seed=95,
      kw='FEES', disc='Costs, caps and surrender schedules vary by carrier, product and state. '
      + D_ILL, p=dict(cy=.34)),
 ]),
 dict(slug='the-transfer-trap', slides=[
   sl('conduit', 'Moving retirement money? One word: *direct.*', 54,
      eyebrow='SLIDE 01 · THE TRANSFER TRAP', seed=61,
      p=dict(severed=False, l1='DIRECT · TRUSTEE TO TRUSTEE')),
   sl('conduit', 'Direct transfer: it never touches your hands.', 54, seed=62,
      p=dict(severed=False, l1='NOT REPORTABLE · NO CLOCK')),
   sl('conduit', 'Indirect: they mail you a check.', 58, seed=63,
      p=dict(severed=True, l1='60-DAY CLOCK', l2='20% WITHHELD')),
   sl('ring60', 'That check starts a 60-day clock.', 58, seed=64,
      p=dict(left=.28, l1='60 DAYS', l2='THEN IT IS TAXABLE')),
   sl('conduit', 'From a 401(k), 20% gets withheld.', 58, seed=65,
      p=dict(severed=True, l1='EMPLOYER PLAN', l2='20% WITHHELD')),
   sl('calendar_ring', 'IRA-to-IRA indirect: once per 12 months.', 54, seed=66,
      p=dict(l1='1 PER 12 MONTHS')),
   sl('vault_teeth', 'Also ask what *leaving* costs you.', 58, seed=67,
      p=dict(labels=['SURRENDER CHARGE', 'MARKET VALUE ADJUSTMENT', 'BONUS RECAPTURE'])),
   sl('mark_end', 'Sometimes the answer is *"wait fourteen months."*', 50, seed=94,
      kw='TRAP', disc=D_TAX + ' Rules can change — confirm with your CPA or tax attorney.',
      p=dict(cy=.34)),
 ]),
]

# ──────────────────────────────────────────────────────────────── REELS (7)
def bt(dur, scene, spoken, size=74, tag=None, seed=1, p=None, **kw):
    d = dict(dur=dur, scene=scene, spoken=spoken, spokenSize=size, seed=seed, p=p or {})
    if tag: d['tag'] = tag
    d.update(kw)
    return d


REELS = [
 dict(slug='the-12-percent-lie', beats=[
   bt(3, 'value_block', 'Why chasing a 12% average is *a sucker’s bet.*', 68,
      tag='REEL 01 · FLOOR', seed=2, p=dict(value='12%', size=150, crackAt=1.6)),
   bt(3, 'hourglass_pair', 'Especially if you’re 55. Let me show you.', 70, seed=8),
   bt(3, 'bar_pair', 'Year one. You’re up *a hundred percent.*', 70, seed=5,
      p=dict(h1=3.0, h2=0.02, t1='YEAR 1  +100%', t2='')),
   bt(3, 'bar_pair', 'Year two. You’re down *fifty.*', 76, seed=6,
      p=dict(h1=3.0, h2=1.5, t1='YEAR 1  +100%', t2='YEAR 2  −50%')),
   bt(3, 'value_block', 'Your guy calls that a *25% average.*', 70, seed=9,
      p=dict(value='25%', size=150, l1='THE AVERAGE')),
   bt(3, 'flatline', 'Your account is exactly *back to even.*', 68, seed=7,
      p=dict(l1='NET CHANGE  $0')),
   bt(3, 'value_block', 'Zero. Two years. *Nothing gained.*', 72, seed=10,
      p=dict(value='$0', size=160)),
   bt(3, 'flatline', 'Averages don’t buy groceries. *Dollars do.*', 66, seed=12,
      p=dict(l1='DOLLARS, NOT AVERAGES')),
   bt(3, 'hourglass_pair', 'At 25 you ride that out.', 78, seed=13,
      p=dict(l1='AGE 25', l2='AGE 55')),
   bt(3, 'hourglass_pair', 'At 55 you *don’t have the years.*', 72, seed=14,
      p=dict(l1='AGE 25', l2='AGE 55')),
   bt(3, 'floor_slab', 'So the floor matters more than *the ceiling.*', 64, seed=3),
   bt(3, 'floor_slab', 'A zero-floor contract can’t lose to the index.', 60, seed=4),
   bt(3, 'capped_column', 'You trade some upside for *a hard bottom.*', 64, seed=11,
      p=dict(level=.7)),
   bt(3, 'capped_column', 'That’s the whole trade. *No magic.*', 70, seed=20,
      p=dict(level=.8)),
   bt(3, 'mark_end', 'Comment *FLOOR.* I’ll run your actual numbers.', 62, seed=99,
      kw='FLOOR', p=dict(cy=.30)),
 ]),
 dict(slug='fixed-vs-income-rider', beats=[
   bt(3, 'pile_vs_paycheck', 'The difference is exactly one word. *Forever.*', 64,
      tag='REEL 02 · RIDER', seed=23),
   bt(3, 'value_block', 'A fixed annuity is *a parking spot.*', 70, seed=24,
      p=dict(value='MYGA', size=118, l1='SET RATE · SET TERM')),
   bt(3, 'bar_pair', 'Money goes in for a set term.', 74, seed=25,
      p=dict(h1=2.2, h2=0.02, t1='PREMIUM', t2='')),
   bt(3, 'bar_pair', 'It earns a stated rate. Term ends.', 70, seed=26,
      p=dict(h1=2.2, h2=2.7, t1='PREMIUM', t2='TERM END')),
   bt(3, 'pile_vs_paycheck', 'You walk with the pile. *Done.*', 74, seed=27),
   bt(3, 'gear_mech', 'An income rider is *a faucet.*', 74, seed=28,
      p=dict(l1='INCOME RIDER', l2='PAID MONTHLY')),
   bt(3, 'fee_stack', 'It’s an optional add-on. *It costs money.*', 64, seed=29,
      p=dict(labels=['RIDER CHARGE', 'ANNUAL'])),
   bt(3, 'value_block', 'Usually under about one percent a year.', 66, seed=30,
      p=dict(value='~1%/YR', size=124, l1='TYPICAL RIDER CHARGE')),
   bt(3, 'wireframe_cube', 'It grows a separate number. *The benefit base.*', 60, seed=31),
   bt(3, 'wireframe_cube', 'That number only *calculates income.*', 66, seed=32,
      p=dict(l1='CASH VALUE', l2='BENEFIT BASE', l3='CALCULATION ONLY')),
   bt(3, 'wireframe_cube', 'You can’t withdraw it as cash.', 74, seed=33,
      p=dict(l1='CASH VALUE', l2='BENEFIT BASE', l3='NOT WITHDRAWABLE')),
   bt(3, 'gear_mech', 'Turn it on, it pays you monthly.', 70, seed=34,
      p=dict(l1='SWITCH IT ON', l2='MONTHLY')),
   bt(3, 'gear_mech', 'For life. *Even after the balance is gone.*', 62, seed=35,
      p=dict(l1='FOR LIFE', l2='EVEN AT $0 VALUE')),
   bt(3, 'pile_vs_paycheck', 'One’s a pile. *One’s a paycheck.*', 70, seed=36),
   bt(3, 'mark_end', 'Comment *RIDER.* I’ll show you both.', 66, seed=98,
      kw='RIDER', p=dict(cy=.30)),
 ]),
 dict(slug='the-20-percent-drop', beats=[
   bt(3, 'twin_columns', 'The S&P drops 20 percent. *Watch two accounts.*', 62,
      tag='REEL 03 · DROP', seed=15, p=dict(a=.8, b=.8, drain=False, va='$100,000', vb='$100,000')),
   bt(3, 'twin_columns', 'Account A sits straight in the market.', 66, seed=16,
      p=dict(a=.8, b=.8, drain=False, va='$100,000', vb='$100,000')),
   bt(3, 'twin_columns', 'A hundred thousand becomes *eighty.*', 70, seed=17,
      p=dict(a=.64, b=.8, drain=False, va='$80,000', vb='$100,000')),
   bt(3, 'twin_columns', 'Account B is index-linked with a zero floor.', 60, seed=18,
      p=dict(a=.64, b=.8, drain=False, va='$80,000', vb='$100,000')),
   bt(3, 'floor_slab', 'Its credit that year is *zero.*', 74, seed=3),
   bt(3, 'value_block', 'Not negative twenty. *Zero.*', 78, seed=19,
      p=dict(value='0.00%', size=132, l1='INDEX CREDIT')),
   bt(3, 'floor_slab', 'The index loss doesn’t take your principal.', 62, seed=4),
   bt(3, 'staircase', 'A now needs 25 percent just to get even.', 62, seed=41,
      p=dict(broken=3, l1='−20% NEEDS +25%')),
   bt(3, 'twin_columns', 'B starts next year at *full value.*', 68, seed=21,
      p=dict(a=.64, b=.8, drain=False, va='$80,000', vb='$100,000')),
   bt(3, 'value_block', 'That’s not magic. *That’s the trade.*', 68, seed=22,
      p=dict(value='THE TRADE', size=74)),
   bt(3, 'capped_column', 'Your upside gets capped. It’s in the contract.', 58, seed=11,
      p=dict(level=.85)),
   bt(3, 'fee_stack', 'Fees and withdrawals can still lower your value.', 58, seed=37,
      p=dict(labels=['WITHDRAWALS', 'RIDER CHARGE'])),
   bt(3, 'value_block', 'No dividends either. *Read the contract.*', 62, seed=38,
      p=dict(value='NO DIVIDENDS', size=72)),
   bt(3, 'staircase', 'But you stop rebuilding *the same hole.*', 64, seed=42,
      p=dict(broken=4, l1='SEQUENCE RISK')),
   bt(3, 'mark_end', 'Comment *DROP.* I’ll send the recovery math.', 62, seed=97,
      kw='DROP', p=dict(cy=.30)),
 ]),
 dict(slug='one-lump-or-two', beats=[
   bt(3, 'value_block', 'One lump or two. *Retirement’s real question.*', 62,
      tag='REEL 04 · LUMP', seed=51, p=dict(value='$300,000', size=104)),
   bt(3, 'split_cube', 'Say you’ve built three hundred thousand.', 66, seed=52,
      p=dict(split=.05, l1='THE PILE', l2='')),
   bt(3, 'split_cube', 'Option one. *You keep the whole lump.*', 66, seed=53,
      p=dict(split=.05, l1='YOU MANAGE IT', l2='')),
   bt(3, 'split_cube', 'You control it. You also manage it.', 68, seed=54,
      p=dict(split=.05, l1='YOUR CALL', l2='')),
   bt(3, 'bar_pair', 'Pull four percent. Twelve thousand a year.', 62, seed=55,
      p=dict(h1=3.0, h2=.5, t1='$300,000', t2='$12,000/YR')),
   bt(3, 'staircase', 'Market drops, that ribbon should *shrink too.*', 62, seed=56,
      p=dict(broken=2, l1='WITHDRAWING INTO A DRAWDOWN')),
   bt(3, 'gear_mech', 'Option two. *Convert part into income.*', 66, seed=57,
      p=dict(l1='LIFETIME PAYOUT', l2='FOR LIFE')),
   bt(3, 'gear_mech', 'Same money through a lifetime payout.', 66, seed=58,
      p=dict(l1='LIFETIME PAYOUT', l2='CONTRACTUAL')),
   bt(3, 'value_block', 'Illustrative payout factor: *five and a half.*', 60, seed=59,
      p=dict(value='5.5%', size=140, l1='ILLUSTRATIVE ONLY')),
   bt(3, 'value_block', 'Sixteen five a year. *For life.*', 68, seed=60,
      p=dict(value='$16,500', size=104, l1='PER YEAR · FOR LIFE')),
   bt(3, 'vault_teeth', 'Trade-off. *Less access to that chunk.*', 64, seed=68,
      p=dict(labels=['LESS LIQUID', 'SURRENDER SCHEDULE'])),
   bt(3, 'split_cube', 'Most people shouldn’t pick one. *Split it.*', 62, seed=69,
      p=dict(split=.42, l1='LIQUID', l2='INCOME')),
   bt(3, 'split_cube', 'Enough income to cover the fixed bills.', 62, seed=70,
      p=dict(split=.42, l1='LIQUID', l2='COVERS THE BILLS')),
   bt(3, 'split_cube', 'The rest stays liquid and still growing.', 62, seed=71,
      p=dict(split=.35, l1='LIQUID', l2='INCOME')),
   bt(3, 'mark_end', 'Comment *LUMP.* I’ll split yours on paper.', 62, seed=96,
      kw='LUMP', p=dict(cy=.30)),
 ]),
 dict(slug='what-fees-actually-cost', beats=[
   bt(3, 'fee_stack', 'Everybody screaming about annuity fees *skips a part.*', 56,
      tag='REEL 05 · FEES', seed=71, p=dict(labels=['RIDER', 'ADMIN', 'SUB-ACCOUNT', 'M&E'])),
   bt(3, 'fee_stack', 'And honestly? Some of them are right.', 64, seed=72,
      p=dict(labels=['RIDER', 'ADMIN', 'SUB-ACCOUNT', 'M&E'])),
   bt(3, 'fee_stack', 'Variable annuities can stack real charges.', 62, seed=73,
      p=dict(labels=['RIDER', 'ADMIN', 'SUB-ACCOUNT', 'M&E'])),
   bt(3, 'fee_stack', 'That’s fair. *I’ll say it out loud.*', 68, seed=74,
      p=dict(labels=['M&E', 'SUB-ACCOUNT', 'RIDER'])),
   bt(3, 'fee_stack', 'A fixed index annuity is *a different animal.*', 60, seed=75,
      p=dict(clean=True, l1='ONE CLEAN CONTRACT')),
   bt(3, 'fee_stack', 'Most base contracts have no explicit annual fee.', 56, seed=76,
      p=dict(clean=True, l1='NO EXPLICIT ANNUAL FEE')),
   bt(3, 'value_block', 'So how does *the carrier get paid?*', 66, seed=77,
      p=dict(value='?', size=170)),
   bt(3, 'capped_column', 'The cap. *That’s the cost.*', 74, seed=11, p=dict(level=.92)),
   bt(3, 'capped_column', 'They keep the upside above your cap.', 62, seed=78,
      p=dict(level=.95, l2='CARRIER KEEPS')),
   bt(3, 'capped_column', 'A real cost. *Just not a line item.*', 64, seed=79,
      p=dict(level=.95, l2='NOT A LINE ITEM')),
   bt(3, 'gear_mech', 'Add an income rider, now you see a fee.', 60, seed=80,
      p=dict(l1='RIDER CHARGE', l2='ANNUAL')),
   bt(3, 'gear_mech', 'Usually under about one percent a year.', 62, seed=81,
      p=dict(l1='RIDER CHARGE', l2='TYP. UNDER ~1%/YR')),
   bt(3, 'ring60', 'Plus surrender charges if you break early.', 60, seed=82,
      p=dict(left=.5, l1='SURRENDER', l2='KNOW THE SCHEDULE')),
   bt(3, 'vault_teeth', 'No free lunch. *Just trade-offs you can read.*', 58, seed=83,
      p=dict(labels=['CAP', 'RIDER CHARGE', 'SURRENDER SCHEDULE'])),
   bt(3, 'mark_end', 'Comment *FEES.* I’ll read the fine print with you.', 56, seed=95,
      kw='FEES', p=dict(cy=.30)),
 ]),
 dict(slug='your-own-pension', beats=[
   bt(3, 'value_block', 'Your grandfather had a pension. *You don’t.*', 62,
      tag='REEL 06 · PENSION', seed=84, p=dict(value='PENSION', size=86, crackAt=1.7)),
   bt(3, 'value_block', 'Here’s how to build *your own version.*', 66, seed=85,
      p=dict(value='D.I.Y.', size=118)),
   bt(3, 'bar_pair', 'A pension is really just three things.', 64, seed=86,
      p=dict(h1=1.6, h2=2.6, t1='MONEY IN', t2='TIME')),
   bt(3, 'gear_mech', 'Money in. Time. *A check for life.*', 68, seed=87,
      p=dict(l1='THREE PARTS', l2='A CHECK FOR LIFE')),
   bt(3, 'fee_stack', 'The company did it with a pooled contract.', 58, seed=88,
      p=dict(labels=['CORPORATE', 'POOLED', 'CLOSED'])),
   bt(3, 'fee_stack', 'You can do it with *a personal one.*', 66, seed=89,
      p=dict(clean=True, l1='ONE PERSONAL CONTRACT')),
   bt(3, 'split_cube', 'You fund it. It sits. It grows.', 68, seed=90,
      p=dict(split=.3, l1='FUNDED', l2='GROWING')),
   bt(3, 'calendar_ring', 'You pick the date you switch it on.', 64, seed=91,
      p=dict(l1='SWITCH-ON DATE')),
   bt(3, 'gear_mech', 'Then the carrier prints you *a monthly check.*', 60, seed=92,
      p=dict(l1='MONTHLY', l2='CONTRACTUAL')),
   bt(3, 'gear_mech', 'It doesn’t stop at 85. *Or 95.*', 70, seed=93,
      p=dict(l1='AGE 85 · 95 · 100', l2='STILL PAYING')),
   bt(3, 'twin_columns', 'The bank pays you interest and a tax form.', 58, seed=100,
      p=dict(a=.5, b=.8, drain=False, va='BANK', vb='CONTRACT')),
   bt(3, 'gear_mech', 'This pays you income *you can’t outlive.*', 62, seed=101,
      p=dict(l1='LIFETIME INCOME', l2='FOR LIFE')),
   bt(3, 'vault_teeth', 'The guarantee is only as strong as the carrier.', 56, seed=102,
      p=dict(labels=['CLAIMS-PAYING ABILITY', 'NOT FDIC INSURED'])),
   bt(3, 'value_block', 'So check the ratings *before you sign.*', 64, seed=103,
      p=dict(value='A.M. BEST', size=76, l1='CHECK THE CARRIER')),
   bt(3, 'mark_end', 'Comment *PENSION.* I’ll build yours on paper.', 60, seed=94,
      kw='PENSION', p=dict(cy=.30)),
 ]),
 dict(slug='the-transfer-trap', beats=[
   bt(3, 'conduit', 'Moving retirement money this year? *One word. Direct.*', 56,
      tag='REEL 07 · TRAP', seed=61, p=dict(severed=False, l1='DIRECT')),
   bt(3, 'conduit', 'There are two ways to move it.', 70, seed=104,
      p=dict(severed=False, l1='TWO WAYS')),
   bt(3, 'conduit', 'Direct transfer. *It never touches your hands.*', 58, seed=105,
      p=dict(severed=False, l1='TRUSTEE TO TRUSTEE')),
   bt(3, 'conduit', 'Indirect. *They cut you a check.*', 68, seed=106,
      p=dict(severed=True, l1='INDIRECT', l2='WITHHOLDING')),
   bt(3, 'ring60', 'That check starts a 60-day clock.', 68, seed=64,
      p=dict(left=.7, l1='60 DAYS', l2='THEN IT IS TAXABLE')),
   bt(3, 'ring60', 'Miss it, *the whole thing becomes taxable.*', 60, seed=107,
      p=dict(left=.08, l1='60 DAYS', l2='TAXABLE')),
   bt(3, 'conduit', 'From a 401k, they withhold twenty percent.', 60, seed=65,
      p=dict(severed=True, l1='EMPLOYER PLAN', l2='20% WITHHELD')),
   bt(3, 'conduit', 'You replace that from your own pocket.', 62, seed=108,
      p=dict(severed=True, l1='REPLACE THE 20%', l2='OUT OF POCKET')),
   bt(3, 'conduit', 'Or you get taxed on *what they kept.*', 64, seed=109,
      p=dict(severed=True, l1='OTHERWISE TAXABLE', l2='20% WITHHELD')),
   bt(3, 'calendar_ring', 'IRA to IRA, indirect is once per year.', 60, seed=66,
      p=dict(l1='1 PER 12 MONTHS')),
   bt(3, 'calendar_ring', 'Do it twice, *the second one’s taxable.*', 62, seed=110,
      p=dict(l1='SECOND ONE: TAXABLE')),
   bt(3, 'vault_teeth', 'Second trap. *What you’re leaving.*', 68, seed=67,
      p=dict(labels=['WHAT DOES LEAVING COST?'])),
   bt(3, 'vault_teeth', 'Surrender charges. Market value adjustments.', 56, seed=111,
      p=dict(labels=['SURRENDER CHARGE', 'MARKET VALUE ADJUSTMENT'])),
   bt(3, 'vault_teeth', 'Always ask what leaving *actually costs.*', 62, seed=112,
      p=dict(labels=['SURRENDER CHARGE', 'MVA', 'BONUS RECAPTURE'])),
   bt(3, 'mark_end', 'Comment *TRAP* before you sign anything.', 62, seed=93,
      kw='TRAP', p=dict(cy=.30)),
 ]),
]

# ─────────────────────────────────────────────────────── REEL COVER FRAMES
REEL_COVERS = [
 dict(slug='the-12-percent-lie', scene='value_block', seed=2, eyebrow='REEL 01 · FLOOR',
      title='The 12% average\nis a *sucker’s bet.*', titleSize=92, sub='45 SEC · COMMENT "FLOOR"',
      p=dict(value='12%', size=150, crackAt=0.1)),
 dict(slug='fixed-vs-income-rider', scene='pile_vs_paycheck', seed=23, eyebrow='REEL 02 · RIDER',
      title='One is a pile.\nOne is a *paycheck.*', titleSize=92, sub='45 SEC · COMMENT "RIDER"'),
 dict(slug='the-20-percent-drop', scene='twin_columns', seed=15, eyebrow='REEL 03 · DROP',
      title='The S&P drops 20%.\n*Watch two accounts.*', titleSize=80, sub='45 SEC · COMMENT "DROP"',
      p=dict(a=.64, b=.8, drain=False, va='$80,000', vb='$100,000')),
 dict(slug='one-lump-or-two', scene='split_cube', seed=51, eyebrow='REEL 04 · LUMP',
      title='One lump\nor *two?*', titleSize=104, sub='45 SEC · COMMENT "LUMP"',
      p=dict(split=.42, l1='LIQUID', l2='INCOME')),
 dict(slug='what-fees-actually-cost', scene='capped_column', seed=11, eyebrow='REEL 05 · FEES',
      title='The cap\n*is the fee.*', titleSize=104, sub='45 SEC · COMMENT "FEES"',
      p=dict(level=.92, l2='CARRIER KEEPS')),
 dict(slug='your-own-pension', scene='gear_mech', seed=87, eyebrow='REEL 06 · PENSION',
      title='Build your own\n*pension.*', titleSize=96, sub='45 SEC · COMMENT "PENSION"',
      p=dict(l1='MONEY IN · TIME · A CHECK', l2='FOR LIFE')),
 dict(slug='the-transfer-trap', scene='conduit', seed=63, eyebrow='REEL 07 · TRAP',
      title='Never let it\n*touch your hands.*', titleSize=88, sub='45 SEC · COMMENT "TRAP"',
      p=dict(severed=True, l1='60-DAY CLOCK', l2='20% WITHHELD')),
]
